title: Mid-MO Amateur Radio Club
email: k0ety@arrl.net
description: >-
  The official website of the Mid-MO Amateur Radio Club (K0ETY) in Jefferson City, MO.
baseurl: "/mmarc-website"
url: "https://kspillane.github.io"
collections:
  minutes:
    output: true
    permalink: /minutes/:year/:month/:title/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:slug/
  operating:
    output: true
    permalink: /operating/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
